name: Data Management Zone Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.tf"

  pull_request:
    branches:
      - main
    paths:
      - "**.tf"

jobs:
  terraform_deploy:
    uses: ./.github/workflows/_terraformEnvironmentTemplate.yml
    name: "Terraform Deploy"
    with:
      environment: "dev"
      terraform_version: "1.10.2"
      node_version: 20
      working_directory: "./tests/e2e"
      tenant_id: "37963dd4-f4e6-40f8-a7d6-24b97919e452"
      subscription_id: "660ed196-9d05-44fc-b902-0c11ca014bd6"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

  terraform_destroy:
    uses: ./.github/workflows/_terraformDestroyTemplate.yml
    name: "Terraform Destroy"
    needs: [terraform_deploy]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
      terraform_version: "1.10.2"
      node_version: 20
      working_directory: "./tests/e2e"
      tenant_id: "37963dd4-f4e6-40f8-a7d6-24b97919e452"
      subscription_id: "660ed196-9d05-44fc-b902-0c11ca014bd6"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
